config/routes.rb
require 'sidekiq/web'

class ProbablyAuthenticated
  def matches?(request)
    request.cookie_jar.signed[:token].present?
  end
end

class CertainlyAnonymous
  def matches?(request)
    !request.cookie_jar.signed[:token].present?
  end
end

class DefinitelyAdmin
  def matches?(request)
    token = request.cookie_jar.signed[:token]
    return false unless token.present?

    user = User.where(token: token).take
    user.present? && user.admin?
  end
end

Rails.application.routes.draw do
  constraints ProbablyAuthenticated.new do
    constraints DefinitelyAdmin.new do
      mount Sidekiq::Web => '/sidekiq'
      get '/admin' => redirect('admin/pages')
      namespace :admin do
        resources :shops, only: [:index, :show] do
          collection do
            get :export
          end
          member do
            post :become
            post :retrial
          end
        end
        resources :discounts, only: [:create, :update]
        resources :pages, only: [:index]
        resources :sites, only: [:show, :index] do
          member do
            post :duplicate
          end
          resources :plans, only: [:create]
          resources :invoices, except: [:index, :show, :destroy]
        end
        resources :users, only: [:index]
      end
    end
    resources :embeds, only: [:show] do
      member do
        get :css
        get :js
      end
    end
    namespace :api do
      resources :sites, only: [:show, :index, :create, :update] do
        member do
          post :users
        end

        resources :invoices, only: [:index] do
          member do
            post :pay
          end
        end

        resources :collaborators, only: [:index, :update, :destroy]
        resources :invites, only: [:index, :destroy]
        resources :models, only: [:index, :create, :update] do
          resources :entries, only: [:create, :destroy, :index, :update]
        end
        resources :templates, only: [:show, :index, :create, :update, :destroy] do
          collection do
            post :parse
          end
        end
        resources :snippets, only: [:create, :destroy, :index]
        resources :pages, only: [:show, :index, :create, :update, :destroy] do
          member do
            post :publish
            post :unpublish
            post :switch_version
            get :version_history
          end
        end
        resources :shopify_pages, only: [:index] do
          member do
            post :import
          end
        end

        resources :shopify_articles, only: [:index] do
          get :blogs, on: :collection
          member do
            post :import
          end
        end
        resources :shopify_templates, only: [:index]
        resources :add_ons, only: [:index, :create, :update]
      end

      resource :user, only: [:show, :update]
    end

    resource :session, only: [:destroy]

    get '/editor/outer' => 'editor#outer'
    get '/editor/inner' => 'editor#inner'

    get '(sites/:id)' => 'app#app', as: :app
    get '(sites/:id)/pages' => 'app#app'
    get '(sites/:id)/templates' => 'app#app'
    get '(sites/:id)/collections' => 'app#app'
    get '(sites/:id)/settings' => 'app#app'
    get '(sites/:id)/settings/billing' => 'app#app'
    get '(sites/:id)/settings/fonts' => 'app#app'
    get '(sites/:id)/settings/users' => 'app#app'
    get '(sites/:id)/settings/integrate' => 'app#app'
    get '(sites/:id)/settings/add_ons' => 'app#app'
    get '(sites/:id)/settings/edit' => 'app#app'
    get '(sites/:id)/templates/new' => 'app#app'
    get '(sites/:id)/pages/new' => 'app#app'
    get '(sites/:id)/pages/layouts' => 'app#app'
    get '(sites/:id)/templates/:id/edit' => 'app#app'
    get '(sites/:id)/collections/:id/edit' => 'app#app'
    get '(sites/:id)/collections/new' => 'app#app'
    get '(sites/:id)/collections/:id/entries/new' => 'app#app'
    get '(sites/:id)/collections/:id/entries/:id/edit' => 'app#app'
    get '(sites/:id)/pages/:id/edit' => 'app#app'
    get '(sites/:id)/pages/:id/duplicate' => 'app#app'

    get 'blogs' => 'app#app'
    get 'blogs/:bid/layouts' => 'app#app'
    get 'blogs/:bid/new' => 'app#app'
    get 'blogs/:bid/article/:pid/edit' => 'app#app'

    get 'sites/new' => 'app#app'
    get 'settings' => 'app#app'
    get 'support' => 'app#app'
  end

  constraints CertainlyAnonymous.new do
    resources :users, only: [:create]
    resource :session, only: [:create]
  end

  resources :invoices, only: [:show] do
    member do
      post :pay
    end
  end

  post "/api/hooks/shopify" => 'api/hooks/shopify#receive', as: :receive_shopify_hook

  match 'auth/failure' => 'sessions#failure', via: [:get]
  match 'auth/shopify/callback' => 'sessions#shopify', via: [:get, :post]
  match 'auth/:provider/callback' => 'sessions#omniauth', via: [:get, :post]

  get 'spendless' => 'cookies#spendless'
  get 'sloyalty20' => 'cookies#sloyalty20'
  get 'guru20' => 'cookies#guru20'

  resources :previews, only: [:show]

  get 'sign_up' => 'users#sign_up', as: :sign_up
  get 'sign_in' => 'users#sign_in', as: :sign_in

  get '/producthunt' => redirect("/")
  get '/unauthenticated' => 'users#sign_in', as: :unauthenticated

  # Heroku add on routes
  # SSO sign in
  get '/heroku/resources/:id' => 'heroku#sso'
  post '/sso/login' => 'heroku#sso'

  # Provision
  post '/heroku/resources' =>  'heroku#provision'

  # Deprovision
  delete '/heroku/resources/:id' => 'heroku#deprovision'

  # Change plan
  put '/heroku/resources/:id' => 'heroku#change_plan'

  get '/logout' => 'sessions#logout'

  get '/users/sign_in' => redirect('/sign_in')

  namespace :shopify do
    get '/proxy/previews/:id' => 'proxy#previews'
    get '/proxy/probe' => 'proxy#probe'

    resources :plans, only: [:index]

    get '/editor/outer' => 'editor#outer'
    get '/editor/inner' => 'editor#inner'

    resources :recurring_charges, only: [:create] do
      collection do
        get :activate
      end
    end
  end

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end
end

app/controllers/admin/shops_controller.rb
require 'csv'

class Admin::ShopsController < ApplicationController
  layout "admin"

  def become
    shop = ShopifyShop.find params[:id]
    user = shop.site.users.shopify.take!
    sign_out!
    sign_in! user
    redirect_to '/'
  end

  def show
    @shop = ShopifyShop.find params[:id]
    @service = @shop.service
    @theme = @service.get_main_theme
    @page_asset = @service.get_theme_asset @theme["id"], "templates/page.liquid"
    @page_liquid = @page_asset["value"]
  end

  def retrial
    shop = ShopifyShop.find params[:id]
    shop.update_column :trialled_at, nil
    flash[:notice] = "Re-trial enabled."
    redirect_to admin_shops_path
  end

  def index
  end

  def export
    string = CSV.generate do |csv|
      csv << ['url', 'name', 'email', 'status', 'plan_name', 'shop_owner', 'signed_up']
      ShopifyShop.order(name: :asc).includes(:active_shopify_charge, site: :plan).each do |shop|
        status = shop.active? ? 'active' : shop.dead? ? 'dead' : 'uninstalled'
        csv << [
          "https://#{shop.domain}",
          shop.name,
          shop.email,
          status,
          shop.site.plan.try(:name),
          shop.shop_owner,
          shop.created_at.in_time_zone(shop.time_zone).to_date
        ]
      end
    end
    render text: string
  end
end

app/views/admin/shops/_revenue.html.haml
- plans = scope.includes(site: :plan).map { |s| s.site.plan }
- plans_by_name = plans.group_by(&:name)
- values_by_name = plans_by_name.each_with_object({}) { |(name, plans), h| h[name] = plans.map(&:price).sum / 100 }
- colors = { 'starter' => '#1CA8DD', 'basic' => '#9F86FF', 'pro' => '#E4D836', 'entry' => '#1CA8DD', 'growth' => '#9F86FF', 'max' => '#E4D836' }
- values = values_by_name.map { |name, value| { value: plans_by_name[name].count, label: name, color: colors[name] } }

.row
  .col-xs-4
    .w-lg.m-x-auto.m-t-md
      %canvas{'data-chart' => 'doughnut', 'data-value' => values.to_json, 'data-segment-stroke-color' => '#fff'}
  .col-xs-8
    .statcard.p-a-md.m-b{class: "statcard-#{cname}"}
      %h3.statcard-number= number_to_currency (plans.map(&:price).sum / 100) * 0.8
      %span.statcard-desc Monthly
    .row
      .col-xs-4
        .statcard.statcard-primary.p-a-md
          %h3.statcard-number= number_to_currency values_by_name['starter'].to_i * 0.8
          %span.statcard-desc Starter

      .col-xs-4
        .statcard.statcard-info.p-a-md
          %h3.statcard-number= number_to_currency values_by_name['basic'].to_i * 0.8
          %span.statcard-desc Basic

      .col-xs-4
        .statcard.statcard-warning.p-a-md
          %h3.statcard-number= number_to_currency values_by_name['pro'].to_i * 0.8
          %span.statcard-desc Pro

    .row
      .col-xs-4
        .statcard.statcard-primary.p-a-md
          %h3.statcard-number= number_to_currency values_by_name['entry'].to_i * 0.8
          %span.statcard-desc Entry

      .col-xs-4
        .statcard.statcard-info.p-a-md
          %h3.statcard-number= number_to_currency values_by_name['growth'].to_i * 0.8
          %span.statcard-desc Growth

      .col-xs-4
        .statcard.statcard-warning.p-a-md
          %h3.statcard-number= number_to_currency values_by_name['max'].to_i * 0.8
          %span.statcard-desc Max

app/views/admin/shops/index.html.haml
.hr-divider.m-t.m-b
  %h3.hr-divider-content.hr-divider-heading
    Conversion

- scope = ShopifyShop.where.not(shopify_plan_name: "staff")

.row
  .col-xs-4
    .statcard.statcard-success.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.count
      %span.statcard-desc Installs

  .col-xs-4
    .statcard.statcard-success.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.with_plan.count
      %span.statcard-desc Chose plan

    .statcard.statcard-info.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.without_plan.active.count
      %span.statcard-desc Pending

    .statcard.statcard-danger.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.without_plan.inactive.not_dead.count
      %span.statcard-desc Uninstalled

    .statcard.statcard-warning.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.without_plan.inactive.dead.count
      %span.statcard-desc Dead

  .col-xs-4
    .statcard.statcard-success.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.with_plan.active.out_of_trial.count
      %span.statcard-desc Converted

    .statcard.statcard-info.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.with_plan.active.in_trial.count
      %span.statcard-desc In trial

    .statcard.statcard-danger.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.with_plan.inactive.not_dead.count
      %span.statcard-desc Uninstalled

    .statcard.statcard-warning.p-a-md.m-b
      %h3.statcard-number= number_with_delimiter scope.with_plan.inactive.dead.count
      %span.statcard-desc Dead

.hr-divider.m-y-md
  %ul.nav.nav-pills.hr-divider-content.hr-divider-nav
    %li
      %a(href="#revenue-trial" data-toggle="tab") Trial
    %li.active
      %a(href="#revenue-current" data-toggle="tab") Current
    %li
      %a(href="#revenue-lost" data-toggle="tab") Lost

.tab-content
  .tab-pane#revenue-trial
    = render partial: 'revenue', locals: {scope: scope.with_plan.active.in_trial, cname: 'info'}

  .tab-pane.active#revenue-current
    = render partial: 'revenue', locals: {scope: scope.with_plan.active.out_of_trial, cname: 'success'}

  .tab-pane#revenue-lost
    = render partial: 'revenue', locals: {scope: scope.with_plan.inactive, cname: 'danger'}


.hr-divider.m-t-md.m-b
  %h3.hr-divider-content.hr-divider-heading
    Shops

%table.table
  %thead
    %tr
      %th.col-xs-3 URL
      %th.col-xs-3 Name
      %th.col-xs-2 Email
      %th.col-xs-2 Status
      %th.col-xs-1 Plan
      %th.col-xs-1 Actions
  %tbody
    - scope.order(name: :asc).includes(:active_shopify_charge, site: :plan).each do |shop|
      %tr
        %td= link_to shop.domain, "https://#{shop.domain}"
        %td= link_to shop.name, admin_shop_path(shop)
        %td= shop.email
        %td
          - if shop.active?
            %span.label.label-success active
          - else
            - if shop.dead?
              %span.label.label-warning dead
            - else
              %span.label.label-danger uninstalled

        %td= shop.site.plan.try(:name)
        %td
          = link_to "become", become_admin_shop_path(shop), method: :post
          - if shop.trialled_at.present?
            = link_to "retrial", retrial_admin_shop_path(shop), method: :post

app/views/admin/shops/show.html.haml
.panel.panel-default
  .panel-heading= @shop.name
  .panel-body
    %ul
      %li= @shop.shop_owner
      %li= @shop.domain
      %li= @shop.email
      %li= @shop.shopify_plan_name
      %li= @shop.time_zone

%h2 Theme #{@theme["name"]}

%h3 Page liquid

%pre= @page_liquid

%h3 Discount
- @shop.site.build_discount unless @shop.site.discount.present?
- discount = @shop.site.discount

- if discount.used? || discount.expired?
  .alert.alert-info Updating this discount make it usable again.
  %p
    - if discount.used?
      %span.label.label-success Used #{discount.used_at}
    - elsif discount.expired?
      %span.label.label-warning Expired #{discount.expires_at}

= simple_form_for [:admin, @shop.site.discount] do |f|
  = f.input :site_id, as: :hidden
  = f.input :amount
  = f.input :plan_name, as: :select, collection: Settings.shopify_plans.keys
  = f.submit