config/routes.rb
require 'sidekiq/web'

class ProbablyAuthenticated
  def matches?(request)
    request.cookie_jar.signed[:token].present?
  end
end

class CertainlyAnonymous
  def matches?(request)
    !request.cookie_jar.signed[:token].present?
  end
end

class DefinitelyAdmin
  def matches?(request)
    token = request.cookie_jar.signed[:token]
    return false unless token.present?

    user = User.where(token: token).take
    user.present? && user.admin?
  end
end

Rails.application.routes.draw do
  constraints ProbablyAuthenticated.new do
    constraints DefinitelyAdmin.new do
      mount Sidekiq::Web => '/sidekiq'
      get '/admin' => redirect('admin/pages')
      namespace :admin do
        resources :shops, only: [:index, :show] do
          collection do
            get :export
          end
          member do
            post :become
            post :retrial
          end
        end
        resources :discounts, only: [:create, :update]
        resources :pages, only: [:index]
        resources :sites, only: [:show, :index] do
          member do
            post :duplicate
          end
          resources :plans, only: [:create]
          resources :invoices, except: [:index, :show, :destroy]
        end
        resources :users, only: [:index]
      end
    end
    resources :embeds, only: [:show] do
      member do
        get :css
        get :js
      end
    end
    namespace :api do
      resources :sites, only: [:show, :index, :create, :update] do
        member do
          post :users
        end

        resources :invoices, only: [:index] do
          member do
            post :pay
          end
        end

        resources :collaborators, only: [:index, :update, :destroy]
        resources :invites, only: [:index, :destroy]
        resources :models, only: [:index, :create, :update] do
          resources :entries, only: [:create, :destroy, :index, :update]
        end
        resources :templates, only: [:show, :index, :create, :update, :destroy] do
          collection do
            post :parse
          end
        end
        resources :snippets, only: [:create, :destroy, :index]
        resources :pages, only: [:show, :index, :create, :update, :destroy] do
          member do
            post :publish
            post :unpublish
            post :switch_version
            get :version_history
          end
        end
        resources :shopify_pages, only: [:index] do
          member do
            post :import
          end
        end

        resources :shopify_articles, only: [:index] do
          get :blogs, on: :collection
          member do
            post :import
          end
        end
        resources :shopify_templates, only: [:index]
        resources :add_ons, only: [:index, :create, :update]
      end

      resource :user, only: [:show, :update]
    end

    resource :session, only: [:destroy]

    get '/editor/outer' => 'editor#outer'
    get '/editor/inner' => 'editor#inner'

    get '(sites/:id)' => 'app#app', as: :app
    get '(sites/:id)/pages' => 'app#app'
    get '(sites/:id)/templates' => 'app#app'
    get '(sites/:id)/collections' => 'app#app'
    get '(sites/:id)/settings' => 'app#app'
    get '(sites/:id)/settings/billing' => 'app#app'
    get '(sites/:id)/settings/fonts' => 'app#app'
    get '(sites/:id)/settings/users' => 'app#app'
    get '(sites/:id)/settings/integrate' => 'app#app'
    get '(sites/:id)/settings/add_ons' => 'app#app'
    get '(sites/:id)/settings/edit' => 'app#app'
    get '(sites/:id)/templates/new' => 'app#app'
    get '(sites/:id)/pages/new' => 'app#app'
    get '(sites/:id)/pages/layouts' => 'app#app'
    get '(sites/:id)/templates/:id/edit' => 'app#app'
    get '(sites/:id)/collections/:id/edit' => 'app#app'
    get '(sites/:id)/collections/new' => 'app#app'
    get '(sites/:id)/collections/:id/entries/new' => 'app#app'
    get '(sites/:id)/collections/:id/entries/:id/edit' => 'app#app'
    get '(sites/:id)/pages/:id/edit' => 'app#app'
    get '(sites/:id)/pages/:id/duplicate' => 'app#app'

    get 'blogs' => 'app#app'
    get 'blogs/:bid/layouts' => 'app#app'
    get 'blogs/:bid/new' => 'app#app'
    get 'blogs/:bid/article/:pid/edit' => 'app#app'

    get 'sites/new' => 'app#app'
    get 'settings' => 'app#app'
    get 'support' => 'app#app'
  end

  constraints CertainlyAnonymous.new do
    resources :users, only: [:create]
    resource :session, only: [:create]
  end

  resources :invoices, only: [:show] do
    member do
      post :pay
    end
  end

  post "/api/hooks/shopify" => 'api/hooks/shopify#receive', as: :receive_shopify_hook

  match 'auth/failure' => 'sessions#failure', via: [:get]
  match 'auth/shopify/callback' => 'sessions#shopify', via: [:get, :post]
  match 'auth/:provider/callback' => 'sessions#omniauth', via: [:get, :post]

  get 'spendless' => 'cookies#spendless'
  get 'sloyalty20' => 'cookies#sloyalty20'
  get 'guru20' => 'cookies#guru20'

  resources :previews, only: [:show]

  get 'sign_up' => 'users#sign_up', as: :sign_up
  get 'sign_in' => 'users#sign_in', as: :sign_in

  get '/producthunt' => redirect("/")
  get '/unauthenticated' => 'users#sign_in', as: :unauthenticated

  # Heroku add on routes
  # SSO sign in
  get '/heroku/resources/:id' => 'heroku#sso'
  post '/sso/login' => 'heroku#sso'

  # Provision
  post '/heroku/resources' =>  'heroku#provision'

  # Deprovision
  delete '/heroku/resources/:id' => 'heroku#deprovision'

  # Change plan
  put '/heroku/resources/:id' => 'heroku#change_plan'

  get '/logout' => 'sessions#logout'

  get '/users/sign_in' => redirect('/sign_in')

  namespace :shopify do
    get '/proxy/previews/:id' => 'proxy#previews'
    get '/proxy/probe' => 'proxy#probe'

    resources :plans, only: [:index]

    get '/editor/outer' => 'editor#outer'
    get '/editor/inner' => 'editor#inner'

    resources :recurring_charges, only: [:create] do
      collection do
        get :activate
      end
    end
  end

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end
end

app/views/shared/_facebook_pixel.html.erb
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script', 'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '538205059712184');
fbq('track', 'PageView');
</script>
<noscript>
  <img height="1" width="1" src="https://www.facebook.com/tr?id=538205059712184&ev=PageView&noscript=1" />
</noscript>
<!-- End Facebook Pixel Code -->

app/views/shared/_flash.html.haml
- if flash[:notice]
  .alert.alert-success.alert-dismissable
    = flash[:notice]

- if flash[:alert]
  .alert.alert-warning.alert-dismissable
    = flash[:alert]

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60251937-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_google_auth.html.haml
%a.google-auth-button{href: "/auth/google_oauth2"}

app/views/shared/_google_remarketing.html.erb
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 940164752;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/940164752/?guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/shared/_navbar.html.haml
%nav{:class => "navbar navbar-default navbar-top shogun-nav"}
  .container
    .navbar-header
      %a{:class => "navbar-brand", :href => "/"}
        .brand
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href: "/#plans", class: "light"}
            Plans
        %li
          %a{href: "/docs", class: "light"}
            Docs
        %li
          %a{href: "/sign_in", class: "light"}
            Sign In

app/views/shared/_plan_setter.html.haml
- if current_user.shopify?
  - if plan = current_user.sites.take.try(:plan)
    - if plan.name == "pro"
      :javascript
        window.HIGH_RES_IMAGES = true

app/views/shared/_segment.html.haml
- if ENV["ENV_NAME"] == "production"
  :javascript
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
    analytics.load("#{ENV['SEGMENT_WRITE_KEY']}");
    }}();
- else
  :javascript
    window.analytics = {
      track: function() {},
      identify: function() {},
      page: function() {}
    }

app/views/shared/_sign_in.html.haml
.box-container
  %h1.light
    Sign In
  = render "/shared/flash"
  .box
    = form_tag session_path, method: :post do
      .form-group
        = render "/shared/google_auth"
      %h3.light
        OR
      .form-group
        %input#sign_in_email.form-control(type="email" name="email" placeholder="Email")
      .form-group
        %input#sign_in_password.form-control(type="password" name="password" placeholder="Password")


      .links
        .form-group
          %input.button.light(type="submit" value="SIGN IN")
        = link_to 'Sign up', sign_up_path, class: "light"

app/views/shared/_sign_up.html.haml
.box-container
  %h1.light
    Sign Up
  = render "/shared/flash"
  .box
    = simple_form_for @user do |f|
      .form-group
        = render "/shared/google_auth"
      %h3.light
        OR
      .row
        .col-sm-6
          = f.input :first_name, placeholder: 'First Name', label: false
        .col-sm-6
          = f.input :last_name, placeholder: 'Last Name', label: false
      = f.input :email, placeholder: 'Email', label: false
      = f.input :company_name, placeholder: 'Company Name', label: false
      = f.input :password, placeholder: 'Password', label: false
      = f.input :password_confirmation, placeholder: 'Password Confirmation', label: false
      .links
        = f.button :submit, "SIGN UP", class: 'button light'
        %br
        = link_to 'Sign in', sign_in_path, class: 'light'